@kong_admin_url = https://api-kong-admin:8444
@kong_url = https://api-kong-proxy:8443

### Query for myapi
{{kong_admin_url}}/apis/httpbin

### Query for oauth2 plugin
{{kong_admin_url}}/plugins/

### Query for plugins on myapi
{{kong_admin_url}}/apis/httpbin/plugins

### Query for consumer amitava
{{kong_admin_url}}/consumers/amitava

### Query for consumers oauth2 plugin
{{kong_admin_url}}/consumers/amitava/oauth2

### Query for consumers oauth2 plugin with a particular client_id
{{kong_admin_url}}/consumers/amitava/oauth2?client_id=myclient

### Invoke authorization flow
curl {{kong_url}}/myapi/oauth2/authorize 
	-H "Host: localhost"
	-H "x-forwarded-proto: https"
	-d "api_id=842dd32f-c795-4fba-8a2a-46c96177036d"
	-d "client_id=myclient"
	-d "response_type=code"
	-d "scope=email phone address"
	-d "provision_key=33ca1ee8-ebfd-4e74-9b49-c55e8ca76694"
	-d "authenticated_userid=amitava"

### Use authorization code from above to get bearer token
curl {{kong_url}}/myapi/oauth2/token
    -d "grant_type=authorization_code"
    -d "client_id=myclient"
    -d "client_secret=ashee007"
    -d "code=1ZJvXGnUVHwrUVQGZWKKAiYE8aSBnQoG"

### Use bearer token (obtained above)
{{kong_url}}/myapi/ip
Authorization: Bearer sSn4jFddUMdQXOAWGN8cmK7ulLAsMQG5

### No joy without Bearer token
{{kong_url}}/myapi/ip

######################################################
# User who has not gone through the authorization flow
@user = jeremy
### Query user
{{kong_admin_url}}/consumers/{{user}}

### Query for consumers oauth2 plugin
{{kong_admin_url}}/consumers/{{user}}/oauth2

### Query for consumers oauth2 plugin with a particular client_id
{{kong_admin_url}}/consumers/{{user}}/oauth2?client_id=bellios

### Invoke authorization flow
curl {{kong_url}}/myapi/oauth2/authorize 
	-H "Host: localhost"
	-H "x-forwarded-proto: https"
	-d "client_id=myclient"
	-d "response_type=code"
	-d "scope=email phone address"
	-d "provision_key=33ca1ee8-ebfd-4e74-9b49-c55e8ca76694"
	-d "authenticated_userid={{user}}"

### Use authorization code from above to get bearer token
curl {{kong_url}}/myapi/oauth2/token
    -d "grant_type=authorization_code"
    -d "client_id=myclient"
    -d "client_secret=ashee007"
    -d "code=t86TD6klehbGnL6wG0F8lZoqCkIx2Pwx"  

### Use bearer token (obtained above)
{{kong_url}}/myapi/ip
Authorization: Bearer yVFiAAVM1s3ijOdbeYkt4BNdR5OcmPp0

### No joy without Bearer token
{{kong_url}}/myapi/ip


##########################################
### oauth flow using userservice


### update redirect
curl -X PATCH {{kong_admin_url}}/consumers/amitava/oauth2/myclient \
    --data "name=Test%20Application" \
    --data "client_id=myclient" \
    --data "client_secret=ashee007" \
    --data "redirect_uri=http://localhost:5000/"
